### ISSUE TITLE
The ANR detector makes the ANR dialog popup late

### ISSUE THREAD

**Issue by yeleaveszi** [bugsnag/bugsnag-android#881] opened 2020-05-12 19:16 UTC
### Expected behavior
ANR dialog popups when ANR happens
### Observed behavior
You must wait 10 seconds for the ANR dialog's popingup once ANR happens
### Steps to reproduce
Just click "TRIGGER AN ANR" button
### Version
Any

Any clue please?

**Comment by mattdyoung** [comment] 2020-05-13 23:17
Can you clarify what the behavior you're seeing is?

Are you just commenting on the way the example app in the bugsnag-android repo artificially attempts to trigger an ANR?

Or have you seen evidence of integrating Bugsnag into a real app affecting the timing of when the ANR dialog is displayed?

**Comment by mattdyoung** [comment] 2020-05-27 23:03
Closing for now pending further feedback on what the issue is.

**Comment by yeleaveszi** [comment] 2020-05-28 06:19
Soory, late to reply.
It's obvious that Bugsnag makes the ANR dialog popup late.
I think we must resend QUIT signal  again manually to slove this problem.
I'm working on it.

**Comment by mattdyoung** [comment] 2020-06-08 09:53
@yeleaveszi - re-opening and we'll investigate further. Thanks!

**Comment by phillipsam** [comment] 2021-01-21 14:22
A update for this has now been released in [v5.5.1](https://github.com/bugsnag/bugsnag-android/releases/tag/v5.5.1).

**Closed by phillipsam** 2021-01-21 14:22 UTC
Labels: needs discussion, scheduled
