### ISSUE TITLE
ANR in 4.13.0

### ISSUE THREAD

**Issue by ColtonIdle** [bugsnag/bugsnag-android#498] opened 2019-06-11 17:17 UTC
### Version
*4.13.0*

### Additional information
**Stacktrace**:

Getting an ANR, and while I can't really pinpoint that BugSnag is the issue, it does show up in the stacktrace in my bugsnag logs. Feel free to close if it's not an issue with BugSnag.

```
ANR: Application did not respond for at least 5000 ms
        at android.os.BinderProxy.transactNative(Binder.java:-2)
        at android.os.BinderProxy.transact(Binder.java:1140)
        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:3560)
        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:143)
        at com.bugsnag.android.ExceptionHandler.uncaughtException(ExceptionHandler.java:91)
        at com.mixpanel.android.mpmetrics.ExceptionHandler.uncaughtException(ExceptionHandler.java:53)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
        at com.uber.rxdogtag.RxDogTag.reportError(RxDogTag.java:309)
        at com.uber.rxdogtag.DogTagObserver.onError(DogTagObserver.java:61)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by fractalwrench** [comment] 2019-06-12 07:48
Hi @ColtonIdle - bugsnag-android added capability for capturing ANRs in v4.13.0 and recently improved it in v4.15.0 to reduce false positives. From inspecting the stacktrace this does looks like a legitimate ANR that bugsnag should capture, therefore I'm closing this ticket as it doesn't seem to be an issue with the bugsnag library.

**Comment by fractalwrench** [comment] 2019-06-13 07:38
I've just noticed that the stacktrace contains a frame for `om.bugsnag.android.ExceptionHandler.uncaughtException` which means this could be an issue with Bugsnag, so am reopening this ticket.

Are you able to reproduce the issue consistently? If not, it would be very helpful to receive a link to this error in your bugsnag dashboard, so we can view error metadata such as thread traces.

**Comment by ColtonIdle** [comment] 2019-06-14 19:05
We actually just released a new version this morning with the updated bugsnag library. I'm going to see if anything comes up and I'll keep you posted. Thanks

**Comment by fractalwrench** [comment] 2019-06-19 08:45
Hi @ColtonIdle - did anything happen with your latest release?

I've noticed that the stacktrace indicates that Bugsnag has called out to the [original exception handler](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/ExceptionHandler.java#L91). Have you set any other custom `UncaughtExceptionHandlers` other than MixPanel?

I'd hypothesise that on older devices installing several exception handlers could block the main thread for long enough to trigger an ANR, although this isn't something we've observed when testing Bugsnag in isolation.

**Comment by ColtonIdle** [comment] 2019-06-19 17:28
Our rollout hasn't hit 100% yet, so I don't have enough data yet. Hoping to report back by early next week.

**Comment by fractalwrench** [comment] 2019-06-28 09:59
Hi @ColtonIdle - do you have any further information on this?

**Comment by fractalwrench** [comment] 2019-07-01 07:53
I am closing this issue as we don't have enough information to determine that this is an issue with Bugsnag and I'm assuming it's now been resolved. Please get in touch if that's not the case.

**Closed by fractalwrench** 2019-07-01 07:53 UTC
