### ISSUE TITLE
Attempt to invoke virtual method 'boolean com.bugsnag.android.Error.shouldIgnoreClass()' on a null object reference

### ISSUE THREAD

**Issue by ghsdh3409** [bugsnag/bugsnag-android#545] opened 2019-07-31 01:53 UTC
### Expected behavior
* I am using `bugsnag-react-native`. In the version `2.22.2` and `2.21.1` that use bugsnag-android `v4.17.1`, `v4.15.0`, it has a crash on some users.
```
Attempt to invoke virtual method 'boolean com.bugsnag.android.Error.shouldIgnoreClass()' on a null object reference
```
### Observed behavior
* The following stacktrace is captured on `v4.15.0`.
```
java.lang.NullPointerException Attempt to invoke virtual method 'boolean com.bugsnag.android.Error.shouldIgnoreClass()' on a null object reference 
    Client.java:901 com.bugsnag.android.Client.notify
    Client.java:203 com.bugsnag.android.Client$2.onErrorReadFailure
    ErrorStore.java:175 com.bugsnag.android.ErrorStore.flushErrorReport
    ErrorStore.java:140 com.bugsnag.android.ErrorStore.flushReports
    ErrorStore.java:125 com.bugsnag.android.ErrorStore$3.run
    ThreadPoolExecutor.java:1162 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:636 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:764 java.lang.Thread.run
```
### Steps to reproduce
* I can't reproduce this error. But, 10% of our users has experienced this crash.

### Version
* `v4.17.1`, `v4.15.0`

### Additional information
* I think the following code block is a problem. Even though https://github.com/bugsnag/bugsnag-android/pull/534 was merged, `error` seems `null`. Is it possible?

https://github.com/bugsnag/bugsnag-android/blob/23f2b4d25a997b5250dd6b371792cef9e8eeb19e/bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java#L890-L896

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by fractalwrench** [comment] 2019-07-31 09:37
Closing as dupe of https://github.com/bugsnag/bugsnag-react-native/issues/381

**Closed by fractalwrench** 2019-07-31 09:37 UTC
