### ISSUE TITLE
Native libraries are include when bugsnag.ndk = false

### ISSUE THREAD

**Issue by kenumir** [bugsnag/bugsnag-android#519] opened 2019-07-10 09:34 UTC
### Expected behavior
When in build.gradle setup:
```
bugsnag {
  ndk false
}
```

### Observed behavior
Libraries `libbugsnag-ndk.so` are included.

When my app not using NDK i dont want to include extra native libraries. Unnecessarily increases the size of the APK file.

**Comment by abigail-bugsnag** [comment] 2019-07-10 15:06
Thanks for your comment @kenumir

This is something that we are currently working on. We will be changing the bundling options for bugsnag-android to separate ANR functionality into its own package so that it can be used with or without the NDK.

**Comment by kenumir** [comment] 2019-07-11 05:53
Temporary solution for now is:
```
ndk {
            abiFilters "x86", "armeabi-v7a", "arm64-v8a", "armeabi"
}
packagingOptions {
            exclude "lib/x86/libbugsnag-ndk.so"
            exclude "lib/armeabi-v7a/libbugsnag-ndk.so"
            exclude "lib/arm64-v8a/libbugsnag-ndk.so"
            exclude "lib/armeabi/libbugsnag-ndk.so"
}
```

**Comment by mattdyoung** [comment] 2019-07-22 09:59
Just to say an update to modularize `bugsnag-android` has how been released in v4.17.0:
https://github.com/bugsnag/bugsnag-android/releases

Details on how to exclude `bugsnag-plugin-android-ndk` and/or `bugsnag-plugin-android-anr` are included in the release notes:
https://github.com/bugsnag/bugsnag-android/releases/tag/v4.17.0

**Closed by mattdyoung** 2019-07-22 09:59 UTC
Labels: feature request, scheduled

**Comment by kenumir** [comment] 2019-07-23 13:08
After update plugin to version 4.5.2 and bungsnag to version 4.17.0 still have `libbugsnag-ndk.so` and `libbugsnag-plugin-android-anr.so` for each architecture.

In manifest file have:
```
<meta-data android:name="com.bugsnag.android.DETECT_NDK_CRASHES" android:value="false"/>
<meta-data android:name="com.bugsnag.android.DETECT_ANRS" android:value="false"/>
```

and `build.gadle`
```
bugsnag {
  ndk false
}
...
implementation("com.bugsnag:bugsnag-android:$version") {
    exclude group: "com.bugsnag", module: "bugsnag-plugin-android-anr"
    exclude group: "com.bugsnag", module: "bugsnag-plugin-android-ndk"
}
```

**Comment by mattdyoung** [comment] 2019-07-24 09:59
The Bugsnag team couldn't reproduce this in 4.17.0. Discussion continuing under https://github.com/bugsnag/bugsnag-android/issues/535
