### ISSUE TITLE
More robust NDK examples

### ISSUE THREAD

**Issue by mariah-smith25** [bugsnag/bugsnag-android#934] opened 2020-09-15 21:59 UTC
### Description

**Describe the solution you'd like**
Looking for more robust examples. The current example only shows reporting an error using the JNI Interface exclusively. Would be nice to have an example of breadcrumbs and error notifies in regular C++ code. I find myself not being able to create breadcrumbs and an error without the "Cannot bugsnag_notify before initializing with bugsnag_start". I put bugsnag_start in my JNI Interface code thinking that would be enough, so I'm not sure where to go from here. I attached screenshots of my code. You can see I try to bugsnag_start before I create my FrequencyEngine. In the FrequencyEngine constructor you can see me trying to test the bugsnag_notify. All calls being made from same thread. If I need to inject env into any method I may need to interact with Bugsnag in the native space that would be helpful to know in documentation (with an example as that's not an easy thing to do).

<img width="523" alt="Screen Shot 2020-09-15 at 4 52 19 PM" src="https://user-images.githubusercontent.com/57910399/93269268-47bc2100-f774-11ea-8561-e5ce47fe7fa5.png">

<img width="780" alt="Screen Shot 2020-09-15 at 4 52 43 PM" src="https://user-images.githubusercontent.com/57910399/93269269-47bc2100-f774-11ea-9bca-340490ce1340.png">

<img width="769" alt="Screen Shot 2020-09-15 at 4 56 26 PM" src="https://user-images.githubusercontent.com/57910399/93269349-69b5a380-f774-11ea-940e-c897a9141408.png">

**Comment by johnkiely1** [comment] 2020-09-25 15:10
@mariah-smith25,
As discussed, this issue has been responded to and resolved via a support request.

For future travellers:
The cause of this error was down to the presence of two similar jni classes, and the bugsnag_start method being called from the wrong one.

**Closed by johnkiely1** 2020-09-25 15:10 UTC
