### ISSUE TITLE
Could not find objdump location, missing .exe extension

### ISSUE THREAD

**Issue by christiancoder** [bugsnag/bugsnag-android#488] opened 2019-05-22 21:53 UTC
On windows I am getting the following gradle build warnings:

Symbolpath: D:\hothead\ballistic_sdk\unity\android\unity2ballisticplugin\build\intermediates\symbols\universal\Final\R.txt
Checking dir: D:\hothead\ballistic_sdk\unity\android\unity2ballisticplugin\build\intermediates\cmake\universal\Final\obj
Found shared object file (arm64-v8a) D:\hothead\ballistic_sdk\unity\android\unity2ballisticplugin\build\intermediates\cmake\universal\Final\obj\arm64-v8a\libunity2ballisticplugin.so
**Error attempting to calculate objdump location: Failed to find executable objdump at C:\NVPACK\android-sdk-windows\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-objdump
Unable to upload NDK symbols: Could not find objdump location for arm64-v8a**
Found shared object file (armeabi-v7a) D:\hothead\ballistic_sdk\unity\android\unity2ballisticplugin\build\intermediates\cmake\universal\Final\obj\armeabi-v7a\libunity2ballisticplugin.so
**Error attempting to calculate objdump location: Failed to find executable objdump at C:\NVPACK\android-sdk-windows\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-objdump
Unable to upload NDK symbols: Could not find objdump location for armeabi-v7a**

Looking at the Groovy code that generates the filename for objdump I noticed it isn't appending the ".exe" extension on windows.

    static File calculateObjDumpLocation(String ndkDir, Abi abi, String osName) {
        new File("$ndkDir/toolchains/$abi.toolchainPrefix-4.9/prebuilt/" +
            "$osName/bin/$abi.objdumpPrefix-objdump")
    }

So I copied the objdump executable file and removed the extension and the build warnings went away. So it looks like you need to add ".exe" to the objdump filename for windows.

I am using version bugsnag-android:4.14.2@aar

**Comment by snmaynard** [comment] 2019-05-23 01:17
I believe this is a duplicate of https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/161

**Closed** 2019-05-23 12:03 UTC

**Comment by tomlongridge** [comment] 2019-05-23 12:05
Duplicate of #161
