### ISSUE TITLE
Endless loop: implement back-off mechanism

### ISSUE THREAD

**Issue by M66B** [bugsnag/bugsnag-android#1253] opened 2021-05-15 16:53 UTC
When somebody uses an ad blocker, VPN, etc the below can happen, which will drain the battery of the device rather soon. Worse, this will use a lot of data!

Related feature request: add a (dynamic) configuration option to disallow metered connections. Somebody was very angry because his monthly mobile data bundle was exhausted in 15 minutes. So, this should be considered as a pretty critical issue.

There should be at least a logarithmic back-off algorithm for this.

```
05-15 12:32:26.480 21110 21144 I Bugsnag : Request completed with code 400, message: Bad Request, headers: {null=[HTTP/1.1 400 Bad Request], Alt-Svc=[clear], Bugsnag-Error-Code=[5], Connection=[close], Content-Length=[15], Content-Type=[text/plain; charset=utf-8], Date=[Sat, 15 May 2021 16:32:27 GMT], Via=[1.1 google], X-Android-Received-Millis=[1621096346480], X-Android-Response-Source=[NETWORK 400], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1621096345708]}
05-15 12:32:26.481 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:26.481 21110 21144 W Bugsnag : java.io.FileNotFoundException: https://notify.bugsnag.com
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:259)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.bugsnag.android.z.e(SourceFile:6)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.bugsnag.android.z.c(SourceFile:7)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.bugsnag.android.z.b(SourceFile:1)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.bugsnag.android.v0.k(SourceFile:6)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.bugsnag.android.v0.n(SourceFile:6)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at com.bugsnag.android.v0$c.run(SourceFile:4)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-15 12:32:26.481 21110 21144 W Bugsnag : 	at java.lang.Thread.run(Thread.java:919)
05-15 12:32:26.482 21110 21144 I Bugsnag : Error API request finished with status UNDELIVERED
05-15 12:32:26.483 21110 21144 W Bugsnag : Could not send previously saved error(s) to Bugsnag, will try again later
05-15 12:32:27.433 21110 21144 W Bugsnag : IOException encountered in request
...
05-15 12:32:28.430 21110 21144 W Bugsnag : IOException encountered in request
...
05-15 12:32:29.361 21110 21144 W Bugsnag : IOException encountered in request
...
05-15 12:32:30.422 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:31.463 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:32.421 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:33.350 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:34.316 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:35.468 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:36.481 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:36.678 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:37.785 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:38.183 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:39.257 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:40.477 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:41.421 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:42.439 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:43.513 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:44.530 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:45.565 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:46.648 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:47.697 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:48.899 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:50.095 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:51.148 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:52.077 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:53.006 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:53.952 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:54.918 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:56.016 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:57.000 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:58.079 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:32:59.046 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:00.268 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:01.264 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:02.226 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:03.274 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:04.307 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:05.325 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:06.331 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:07.260 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:08.197 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:09.227 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:10.317 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:11.446 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:12.507 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:13.502 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:14.497 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:15.532 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:16.926 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:17.960 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:18.997 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:20.078 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:21.122 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:22.269 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:23.283 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:24.230 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:25.262 21110 21144 W Bugsnag : IOException encountered in request
05-15 12:33:26.253 21110 21144 W Bugsnag : IOException encountered in request
```

**Comment by M66B** [comment] 2021-05-15 21:01
More info:

```
05-15 13:45:37.916 24676 24707 I Bugsnag : Request completed with code 400, message: Bad Request, headers: {null=[HTTP/1.1 400 Bad Request], Alt-Svc=[clear], Bugsnag-Error-Code=[5], Content-Length=[15], Content-Type=[text/plain; charset=utf-8], Date=[Sat, 15 May 2021 17:45:38 GMT], Via=[1.1 google], X-Android-Received-Millis=[1621100737916], X-Android-Response-Source=[NETWORK 400], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1621100737038]}
05-15 13:45:37.919 24676 24707 W Bugsnag : IOException encountered in request
05-15 13:45:37.919 24676 24707 W Bugsnag : java.io.FileNotFoundException: https://notify.bugsnag.com
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:259)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.bugsnag.android.a0.e(SourceFile:6)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.bugsnag.android.a0.c(SourceFile:7)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.bugsnag.android.a0.b(SourceFile:1)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.bugsnag.android.w0.k(SourceFile:6)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.bugsnag.android.w0.n(SourceFile:6)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at com.bugsnag.android.w0$c.run(SourceFile:4)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-15 13:45:37.919 24676 24707 W Bugsnag : 	at java.lang.Thread.run(Thread.java:919)
05-15 13:45:37.921 24676 24707 I Bugsnag : Error API request finished with status UNDELIVERED
05-15 13:45:37.924 24676 24707 W Bugsnag : Could not send previously saved error(s) to Bugsnag, will try again later
```

**Comment by yousif-bugsnag** [comment] 2021-05-17 14:58
Hi @M66B,

It looks like in this case Bugsnag would have been inaccessible (or down) due to the adblocker configuration. Bugsnag will retry delivery of undelivered payloads, but only when one of the following occurs:

- A new error is captured
- The network connectivity changes
- The app is launched

So we suspect that one or more of these conditions was met for this user. Are you able to reproduce the issue?

**Comment by M66B** [comment] 2021-05-17 15:02
It is pretty unlikely that about every second:

* A new error is captured
* The network connectivity changes
* The app is launched

Isn't Bugsnag itself causing a new error internally?

This logging is coming from a user's device. I haven't tried to reproduce this myself, but I guess a "throw new IOError" would be sufficient to reproduce this.

**Comment by M66B** [comment] 2021-05-17 16:12
I have tried to reproduce this by adding this to the start of *makeRequest*:

```
throw FileNotFoundException("Test");
```

and I can't reproduce the issue.

Yet, this was happening in practice, causing the battery of the device to be drained fast.

**Comment by johnkiely1** [comment] 2021-05-21 13:13
Hi @M66B 
Without have a reproduction case, it's difficult for us to understand the exact circumstances in which this occurs. Is there any additional information you can share? Do you know any more about which adblocker/configuration was used?

**Comment by M66B** [comment] 2021-05-21 18:59
Does this help in any way?

```
05-15 13:45:51.571 24676 24707 W Bugsnag : IOException encountered in request
05-15 13:45:51.571 24676 24707 W Bugsnag : javax.net.ssl.SSLException: Write error: ssl=0x7846e06888: I/O error during system call, Broken pipe
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:660)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.okhttp.okio.Okio$1.write(Okio.java:85)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:177)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:47)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:497)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:177)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:199)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at java.io.OutputStream.write(OutputStream.java:75)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.bugsnag.android.a0.f(SourceFile:9)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.bugsnag.android.a0.c(SourceFile:4)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.bugsnag.android.a0.b(SourceFile:1)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.bugsnag.android.w0.k(SourceFile:6)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.bugsnag.android.w0.n(SourceFile:6)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at com.bugsnag.android.w0$c.run(SourceFile:4)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	at java.lang.Thread.run(Thread.java:919)
05-15 13:45:51.571 24676 24707 W Bugsnag : 	Suppressed: javax.net.ssl.SSLException: Write error: ssl=0x7846e06888: I/O error during system call, Broken pipe
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:660)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.okhttp.okio.Okio$1.write(Okio.java:85)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:177)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:47)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.okhttp.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:497)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.okhttp.okio.RealBufferedSink.close(RealBufferedSink.java:235)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.android.okhttp.okio.RealBufferedSink$1.close(RealBufferedSink.java:210)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at c.o.a.a(SourceFile:2)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		at com.bugsnag.android.a0.f(SourceFile:11)
05-15 13:45:51.571 24676 24707 W Bugsnag : 		... 10 more
05-15 13:45:51.572 24676 24707 I Bugsnag : Error API request finished with status UNDELIVERED
```

**Comment by M66B** [comment] 2021-05-24 08:33
The app limits the number of error reports to 5 per 4 hour per device. So, in any case the app isn't triggering this.

Maybe there are multiple network events. Note that *onAvailable* in *ConnectivityCompat* doesn't call *hasNetworkConnection*. In my experience, things in different Android versions do not always work as documented or anticipated.

Another idea: maybe breadcrumbs are causing this?

Anyway, I think it would be a good idea to at least wait a little after a failure. This could be done with a simple variable like *lastAttempt* and there could be another variable like *backoffDelay*, which could be doubled up to a maximum with each failed attempt and be reset after a successful attempt.

**Comment by mattdyoung** [comment] 2021-05-26 12:01
@M66B - we're planning to look into this a bit further to see if we can reproduce a different way. We don't believe breadcrumbs would cause this but we can look into other possibilities.

**Comment by johnkiely1** [comment] 2021-06-18 14:25
Hi @M66B 

We have tried a number of additional things and are still unable to reproduce this error. 
Based on your initial comment it sounds like it was only a single user that encountered this problem. This is not something we have seen for any other customer so it may be device or user specific.

Unfortunately at this point there is not a lot more we can do without an exact reproduction example in order to investigate further.

Feel free to write in to support@bugsnag.com if you do get any more details that might help us reproduce. I will close this issue for now.

**Closed by johnkiely1** 2021-06-18 14:25 UTC
